# 1. 修改顶部导航菜单 (注意缩进!)
menu:
  首页: / || fas fa-home
  归档: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
  清单:
    音乐: /music/ || fas fa-music
    影视: /movies/ || fas fa-video
    动画: /anime/ || fas fa-film
    游戏: /games/ || fas fa-gamepad
    书单: /books/ || fas fa-book
  关于: /about/ || fas fa-heart

# 2. 修改个人信息卡片 (侧边栏那个)
avatar:
  img: /img/avatar.jpg # 可以是网络图片，也可以是 /img/avatar.jpg
  effect: true # 头像会转动！

social:
  fab fa-github: https://github.com/xxxxx || Github || "#hdhfbb"
  fab fa-bilibili: https://www.bilibili.com/ || bilibili || "#23ade5"


aside:
  # 是否啟用側邊欄
  enable: true
  # 是否默認隱藏側邊欄
  hide: false
  # 是否在右下角顯示隱藏側邊欄的按鈕
  button: true
  # 移動設備上是否啟用側邊欄
  mobile: true
  # 側邊欄位置：left / right
  position: right
  display:
    # 歸檔頁面是否顯示側邊欄
    archive: true
    # 標籤頁面是否顯示側邊欄
    tag: true
    # 分類頁面是否顯示側邊欄
    category: true
  card_author:
    # 是否顯示作者信息卡片
    enable: true
    # 作者描述
    description:
    button:
      # 是否顯示按鈕
      enable: true
      # 按鈕圖標
      icon: fab fa-github
      # 按鈕文本
      text: Follow Me
      # 按鈕鏈接
      link: https://github.com/HeiSha-NZH