# 1. 修改顶部导航菜单 (注意缩进!)
menu:
  首页: / || fas fa-home
  # 归档: /archives/ || fas fa-archive
  # 标签: /tags/ || fas fa-tags
  # 分类: /categories/ || fas fa-folder-open
  日常记录:
    摄影: /categories/photos/ || fas fa-camera
  清单:
    音乐: /categories/music/ || fas fa-music
    影视: /categories/movies/ || fas fa-video
    动画: /categories/anime/ || fas fa-film
    游戏: /categories/games/ || fas fa-gamepad
    书单: /categories/books/ || fas fa-book
  # 关于: /about/ || fas fa-heart

# 2. 修改个人信息卡片 (侧边栏那个)
avatar:
  img: /img/avatar.jpg # 可以是网络图片，也可以是 /img/avatar.jpg
  effect: true # 头像会转动！

social:
  fab fa-github: https://github.com/HeiSha-NZH || Github || "#hdhfbb"
  fab fa-bilibili: https://space.bilibili.com/19236364 || bilibili || "#23ade5"


aside:
  # 是否啟用側邊欄
  enable: true
  # 是否默認隱藏側邊欄
  hide: false
  # 是否在右下角顯示隱藏側邊欄的按鈕
  button: true
  # 移動設備上是否啟用側邊欄
  mobile: true
  # 側邊欄位置：left / right
  position: right
  display:
    # 歸檔頁面是否顯示側邊欄
    archive: true
    # 標籤頁面是否顯示側邊欄
    tag: true
    # 分類頁面是否顯示側邊欄
    category: true
  card_author:
    # 是否顯示作者信息卡片
    enable: true
    # 作者描述
    description:
    button:
      # 是否显示按钮
      enable: false
  card_announcement:
    enable: false

post_copyright:
  # 是否启用版权声明
  enable: false

reward:
  # 打赏赞助页面
  enable: false
  text:
  QR_code:
    - img: /img/wechat.jpg
      link:
      text: 微信
    - img: /img/alipay.jpg
      link:
      text: 支付宝

share:
  # 两种分享方式: sharejs / addtoany
  # 不需要分享请留空
  use: 
